### ISSUE TITLE
CLA 자동으로 반영되도록 구성

### ISSUE THREAD

**Issue by chaeya** [hamonikr/hamonize#7]
아래 사이트를 참고해서 모든 기여자의 라이선스 동의를 기본적으로 포함할 수 있도록 적용
https://colineberhardt.github.io/cla-bot/

**Comment by chaeya** [comment]
CLA 봇이 남기는 코멘트를 트리거로 코멘트를 다는 방법은 아래 액션을 참고하세요
https://github.com/marketplace/actions/auto-comment

**Comment by chaeya** [comment]
특정 조건에 트리거를 이용해서 코멘트를 남기는 액션의 예는 아래 링크를 참고.
https://github.com/marketplace/actions/pull-request-add-comment

```
name: Example

on: 
  pull_request:
  issue_comment:
    types: [created, edited]

jobs:
  example_comment_pr:
    runs-on: ubuntu-latest
    name: An example job to comment a PR
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Comment PR
        uses: allthatjazzleo/actions-pull-request-add-comment@master
        if: >-
          github.event_name == 'pull_request' || (github.event_name == 'issue_comment' 
          && github.event.comment.body == '/hi' && github.actor == 'allthatjazzleo' )
        with:
          message: 'yoyo🤙🏻'
          # message: "echo ${{ github.event.comment.body }}' dynamic message
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

```
